"""Initial schema

Revision ID: 9e405d10b8e3
Revises: 
Create Date: 2026-06-16 21:19:08.508611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e405d10b8e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('dates', sa.Text(), nullable=False),
    sa.Column('n_episodes', sa.Integer(), nullable=False),
    sa.Column('compare_with', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_jobs_created_at', 'evaluation_jobs', ['created_at'], unique=False)
    op.create_index('ix_eval_jobs_status', 'evaluation_jobs', ['status'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_model', sa.String(length=20), nullable=False),
    sa.Column('strategies', sa.Text(), nullable=False),
    sa.Column('n_paths', sa.Integer(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('lob_file_id', sa.String(length=36), nullable=True),
    sa.Column('agg_file_id', sa.String(length=36), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sim_jobs_created_at', 'simulation_jobs', ['created_at'], unique=False)
    op.create_index('ix_sim_jobs_status', 'simulation_jobs', ['status'], unique=False)
    op.create_table('sweep_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sweep_dimension', sa.String(length=30), nullable=False),
    sa.Column('grid_values', sa.Text(), nullable=False),
    sa.Column('n_paths', sa.Integer(), nullable=False),
    sa.Column('strategies', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sweep_jobs_created_at', 'sweep_jobs', ['created_at'], unique=False)
    op.create_index('ix_sweep_jobs_status', 'sweep_jobs', ['status'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('date_str', sa.String(length=10), nullable=True),
    sa.Column('n_rows', sa.Integer(), nullable=True),
    sa.Column('preview_data', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('uploaded_models')
    op.drop_table('uploaded_files')
    op.drop_index('ix_sweep_jobs_status', table_name='sweep_jobs')
    op.drop_index('ix_sweep_jobs_created_at', table_name='sweep_jobs')
    op.drop_table('sweep_jobs')
    op.drop_index('ix_sim_jobs_status', table_name='simulation_jobs')
    op.drop_index('ix_sim_jobs_created_at', table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index('ix_eval_jobs_status', table_name='evaluation_jobs')
    op.drop_index('ix_eval_jobs_created_at', table_name='evaluation_jobs')
    op.drop_table('evaluation_jobs')
    # ### end Alembic commands ###
